import type { Play } from "@/lib/shared/types";

/* ── คลัง Play ตั้งต้น ─────────────────────────────────────────
   15 KEEP + 8 REACH · Play Engine §2 · §3 · ภาคผนวก

   ทั้งหมดเป็น "ข้อมูล" ไม่ใช่ตรรกะที่ฝังในโค้ด — เพิ่ม play ใหม่
   เท่ากับเพิ่มแถว ไม่ใช่ deploy นี่คือเส้นแบ่งระหว่างโปรเจกต์
   กับผลิตภัณฑ์
   ───────────────────────────────────────────────────────────── */

const KEEP_DEFAULTS = {
  measurement: "auto" as const,
  channel: "line_1to1",
};

export const KEEP_PLAYS: Play[] = [
  {
    ...KEEP_DEFAULTS,
    id: "vip_care",
    engine: "keep",
    name: "Look after your biggest spenders",
    logic: "The top 10% by lifetime spend",
    crossIndustry: "Golf champions · VIP patients",
    cycle_shape: ["replenishment", "recall", "expiry", "considered"],
    selector: {
      monetary_percentile_min: 90,
      discount_affinity: ["full_price", "mixed"],
      reachable_by: ["line"],
      consent_marketing: true,
    },
    guards: { min_audience: 20, cooldown_days: 45, max_discount_pct: 0 },
    offer: { type: "status_privilege", fallback: "early_access" },
    copy_brief: {
      angle: "First look at new stock, not a discount",
      avoid: ["Discounting", "Urgency"],
    },
    priors: { response_rate: 0.22 },
    expected_order_value: 2800,
  },
  {
    ...KEEP_DEFAULTS,
    id: "high_value_slipping",
    engine: "keep",
    name: "High value, drifting",
    logic: "High value, past their own cycle",
    crossIndustry: "Gold, drifting",
    cycle_shape: ["replenishment", "recall", "considered"],
    selector: {
      monetary_percentile_min: 65,
      churn_risk_min: 1.3,
      churn_risk_max: 2.5,
      reachable_by: ["line"],
      consent_marketing: true,
    },
    guards: { min_audience: 30, cooldown_days: 30, max_discount_pct: 10 },
    offer: { type: "personal_checkin", fallback: "small_credit" },
    copy_brief: {
      angle: "It has been a while — something you would like is waiting",
      avoid: ["Blame", "Deep discounts"],
    },
    priors: { response_rate: 0.14 },
    expected_order_value: 2400,
  },
  {
    ...KEEP_DEFAULTS,
    id: "cross_sell_after_anchor",
    engine: "keep",
    name: "Attach after the anchor",
    logic: "Bought A, never bought the B that follows",
    crossIndustry: "Driver → balls · tyres → alignment · scaling → care kit",
    cycle_shape: ["replenishment", "recall", "considered"],
    selector: {
      bought_group: "anchor",
      not_bought_group: "attachment",
      days_since_anchor: [3, 45],
      consent_marketing: true,
      reachable_by: ["line"],
    },
    guards: { min_audience: 50, cooldown_days: 30, max_discount_pct: 15 },
    offer: { type: "attachment_bundle", fallback: "free_shipping" },
    copy_brief: {
      angle: "The pair is one piece short",
      avoid: ["Urgency", "Deep discounts"],
    },
    priors: { response_rate: 0.08 },
    expected_order_value: 1500,
  },
  {
    ...KEEP_DEFAULTS,
    id: "service_to_product",
    engine: "keep",
    name: "From service to product",
    logic: "Used the service, bought no product",
    crossIndustry: "Fitted but no club · spa but no cream",
    cycle_shape: ["recall", "considered"],
    selector: {
      used_service_no_product: true,
      consent_marketing: true,
      reachable_by: ["line"],
    },
    guards: { min_audience: 25, cooldown_days: 21, max_discount_pct: 10 },
    offer: { type: "fitted_product_offer", fallback: "consultation" },
    copy_brief: {
      angle: "Already measured — all that is left is choosing what matches",
      avoid: ["Hard selling", "Deep discounts"],
    },
    priors: { response_rate: 0.19 },
    expected_order_value: 8500,
  },
  {
    ...KEEP_DEFAULTS,
    id: "tier_nudge",
    engine: "keep",
    name: "Push to the next tier",
    logic: "One step short of the next tier",
    crossIndustry: "One more order reaches Platinum",
    cycle_shape: ["replenishment", "recall", "expiry"],
    selector: {
      tier_gap_max: 3000,
      consent_marketing: true,
      reachable_by: ["line"],
    },
    guards: { min_audience: 20, cooldown_days: 60, max_discount_pct: 0 },
    offer: { type: "tier_progress", fallback: "bonus_points" },
    copy_brief: {
      angle: "Almost at the next tier",
      avoid: ["Pressure", "Countdown"],
    },
    priors: { response_rate: 0.16 },
    expected_order_value: 3200,
  },
  {
    ...KEEP_DEFAULTS,
    id: "welcome_no_purchase",
    engine: "keep",
    name: "Signed up, never bought",
    logic: "Signed up, no purchase in 30 days",
    crossIndustry: "Every business",
    cycle_shape: ["replenishment", "recall", "expiry", "considered"],
    selector: {
      signed_up_days: [7, 45],
      no_purchase_ever: true,
      consent_marketing: true,
      reachable_by: ["line"],
    },
    guards: { min_audience: 20, cooldown_days: 30, max_discount_pct: 15 },
    offer: { type: "first_purchase_incentive", fallback: "welcome_guide" },
    copy_brief: {
      angle: "You are signed up — try your first benefit",
      avoid: ["Chasing"],
    },
    priors: { response_rate: 0.11 },
    expected_order_value: 1200,
  },
  {
    ...KEEP_DEFAULTS,
    id: "affinity_new_arrival",
    engine: "keep",
    name: "New arrivals matching their taste",
    logic: "Shown affinity plus new stock",
    crossIndustry: "Brand loyalists · patients on the same brand",
    cycle_shape: ["replenishment", "considered"],
    selector: {
      affinity_new_arrival: true,
      consent_marketing: true,
      reachable_by: ["line"],
    },
    guards: { min_audience: 40, cooldown_days: 21, max_discount_pct: 0 },
    offer: { type: "new_arrival_preview", fallback: "restock_alert" },
    copy_brief: {
      angle: "A new model just landed in the brand you use",
      avoid: ["Price cuts"],
    },
    priors: { response_rate: 0.13 },
    expected_order_value: 2100,
  },
  {
    ...KEEP_DEFAULTS,
    id: "browser_to_buyer",
    engine: "keep",
    name: "Comes often, buys little",
    logic: "Frequent, low spend",
    crossIndustry: "Visits often, never buys",
    cycle_shape: ["considered", "replenishment"],
    selector: {
      visit_to_purchase_ratio_min: 4,
      consent_marketing: true,
      reachable_by: ["line"],
    },
    guards: { min_audience: 30, cooldown_days: 30, max_discount_pct: 10 },
    offer: { type: "assisted_selection", fallback: "trial" },
    copy_brief: {
      angle: "You visit often — shall we help you choose?",
      avoid: ["Calling them out", "Deep discounts"],
    },
    priors: { response_rate: 0.09 },
    expected_order_value: 1800,
  },
  {
    ...KEEP_DEFAULTS,
    id: "lifecycle_moment",
    engine: "keep",
    name: "Personal milestones",
    logic: "Birthday, anniversary, signup date",
    crossIndustry: "Every business",
    cycle_shape: ["replenishment", "recall", "expiry", "considered"],
    selector: {
      lifecycle_within_days: 14,
      consent_marketing: true,
      reachable_by: ["line"],
    },
    guards: { min_audience: 10, cooldown_days: 300, max_discount_pct: 20 },
    offer: { type: "birthday_privilege", fallback: "greeting" },
    copy_brief: { angle: "Greet first, offer second", avoid: ["Selling before greeting"] },
    priors: { response_rate: 0.24 },
    expected_order_value: 1900,
  },
  {
    ...KEEP_DEFAULTS,
    id: "dormant_reactivation",
    engine: "keep",
    name: "Wake the long-silent",
    logic: "Silent past 2.5× their own cycle",
    crossIndustry: "Silent past six months",
    cycle_shape: ["replenishment", "recall", "considered"],
    selector: {
      cycle_multiple_min: 2.5,
      consent_marketing: true,
      reachable_by: ["line"],
    },
    guards: { min_audience: 50, cooldown_days: 90, max_discount_pct: 20 },
    offer: { type: "reactivation_offer", fallback: "whats_new" },
    copy_brief: {
      angle: "Wake them with what they bought, not what we want to clear",
      avoid: ["Guilt", "Counting days away"],
    },
    priors: { response_rate: 0.06 },
    expected_order_value: 2200,
  },
  {
    ...KEEP_DEFAULTS,
    id: "replenishment_due",
    engine: "keep",
    name: "Replenishment due",
    logic: "At the predicted repeat date",
    crossIndustry: "Supplements · pet food · coffee",
    cycle_shape: ["replenishment"],
    selector: {
      predicted_next_within_days: 7,
      churn_risk_max: 1.2,
      consent_marketing: true,
      reachable_by: ["line"],
    },
    guards: { min_audience: 40, cooldown_days: 14, max_discount_pct: 5 },
    offer: { type: "reorder_shortcut", fallback: "reminder" },
    copy_brief: {
      angle: "What you use is probably running low — reorder in one tap",
      avoid: ["Cross-sell"],
    },
    priors: { response_rate: 0.27 },
    expected_order_value: 1400,
  },
  {
    ...KEEP_DEFAULTS,
    id: "expiry_approaching",
    engine: "keep",
    name: "Expiring soon",
    logic: "Membership, course or policy near its end",
    crossIndustry: "Gyms · schools · insurance",
    cycle_shape: ["expiry"],
    selector: {
      expiry_within_days: 30,
      consent_marketing: true,
      reachable_by: ["line"],
    },
    guards: { min_audience: 20, cooldown_days: 30, max_discount_pct: 15 },
    offer: { type: "renewal", fallback: "extension" },
    copy_brief: {
      angle: "Ranked by value at risk, not by date",
      avoid: ["Fear"],
    },
    priors: { response_rate: 0.31 },
    expected_order_value: 4500,
  },
  {
    ...KEEP_DEFAULTS,
    id: "recall_due",
    engine: "keep",
    name: "Service due",
    logic: "Service cycle from the last visit",
    crossIndustry: "Dental · oil change · pet vaccination",
    cycle_shape: ["recall"],
    selector: {
      recall_within_days: 21,
      consent_marketing: true,
      reachable_by: ["line"],
    },
    guards: { min_audience: 20, cooldown_days: 30, max_discount_pct: 10 },
    offer: { type: "booking_slot", fallback: "reminder" },
    copy_brief: {
      angle: "You are due — book ahead now",
      avoid: ["Upsell"],
    },
    priors: { response_rate: 0.29 },
    expected_order_value: 2600,
  },
  {
    ...KEEP_DEFAULTS,
    id: "dead_stock_match",
    engine: "keep",
    name: "Match dead stock",
    logic: "Dead stock × people who buy that category on discount",
    crossIndustry: "All retail",
    cycle_shape: ["replenishment", "considered"],
    selector: {
      dead_stock_match: true,
      discount_affinity: ["discount_seeker", "mixed"],
      consent_marketing: true,
      reachable_by: ["line"],
    },
    guards: { min_audience: 30, cooldown_days: 45, max_discount_pct: 40 },
    offer: { type: "clearance_match", fallback: "bundle" },
    copy_brief: {
      angle: "The category you follow is reduced this round",
      avoid: ["Calling it dead stock"],
    },
    priors: { response_rate: 0.12 },
    expected_order_value: 900,
  },
  {
    ...KEEP_DEFAULTS,
    id: "referral_champion",
    engine: "keep",
    name: "Ask champions to refer",
    logic: "High value, frequent, never referred",
    crossIndustry: "Every business",
    cycle_shape: ["replenishment", "recall", "expiry", "considered"],
    selector: {
      monetary_percentile_min: 80,
      frequency_90d_min: 2,
      never_referred: true,
      consent_marketing: true,
      reachable_by: ["line"],
    },
    guards: { min_audience: 20, cooldown_days: 120, max_discount_pct: 10 },
    offer: { type: "referral_reward", fallback: "thanks" },
    copy_brief: {
      angle: "Thank you for coming back — bring a friend?",
      avoid: ["Sounding like a salesperson"],
    },
    priors: { response_rate: 0.1 },
    expected_order_value: 2800,
  },
];

const REACH_DEFAULTS = {
  measurement: "auto" as const,
  channel: "audience_export",
};

export const REACH_PLAYS: Play[] = [
  {
    ...REACH_DEFAULTS,
    id: "seed_repeat_full_price",
    engine: "reach",
    name: "Seed from full-price repeat buyers",
    logic: "Repeat and full price, not the highest spenders",
    crossIndustry: "Every cycle",
    cycle_shape: ["replenishment", "recall", "expiry", "considered"],
    selector: {
      repeat_buyer: true,
      discount_affinity: ["full_price"],
      consent_marketing: true,
    },
    guards: { min_audience: 100, cooldown_days: 30, max_discount_pct: 0 },
    offer: { type: "lookalike_seed" },
    copy_brief: {
      angle: "The signature of the customers who keep the shop alive",
      avoid: ["Using top spenders as the template"],
    },
    priors: { response_rate: 0.03 },
    expected_order_value: 2600,
  },
  {
    ...REACH_DEFAULTS,
    id: "seed_by_anchor_sku",
    engine: "reach",
    name: "Seed from the gateway product",
    logic: "People who started from the same gateway product",
    crossIndustry: "Find people who will walk the same path",
    cycle_shape: ["considered", "replenishment"],
    selector: { anchor_starter: true, repeat_buyer: true, consent_marketing: true },
    guards: { min_audience: 80, cooldown_days: 30, max_discount_pct: 0 },
    offer: { type: "lookalike_seed" },
    copy_brief: { angle: "A path that starts from the same item", avoid: [] },
    priors: { response_rate: 0.028 },
    expected_order_value: 3100,
  },
  {
    ...REACH_DEFAULTS,
    id: "seed_high_ltv",
    engine: "reach",
    name: "Find more like your best 10%",
    logic: "Your top 10% by spend only — a small list, but the highest quality one you have",
    crossIndustry: "For a limited budget",
    cycle_shape: ["replenishment", "recall", "expiry", "considered"],
    selector: { ltv_decile_min: 10, consent_marketing: true },
    guards: { min_audience: 50, cooldown_days: 30, max_discount_pct: 0 },
    offer: { type: "lookalike_seed" },
    copy_brief: { angle: "Small, high quality", avoid: [] },
    priors: { response_rate: 0.035 },
    expected_order_value: 4200,
  },
  {
    ...REACH_DEFAULTS,
    id: "suppress_existing",
    engine: "reach",
    name: "Suppress existing customers from ad spend",
    logic: "Stop paying to reach people who already bought",
    crossIndustry: "Every cycle — a play that saves money rather than spending it",
    cycle_shape: ["replenishment", "recall", "expiry", "considered"],
    selector: { repeat_buyer: false, consent_marketing: true },
    guards: { min_audience: 1, cooldown_days: 7, max_discount_pct: 0 },
    offer: { type: "suppression_list" },
    copy_brief: { angle: "No copy — this is a suppression list", avoid: [] },
    priors: { response_rate: 1 },
    expected_order_value: 0,
  },
  {
    ...REACH_DEFAULTS,
    id: "suppress_bad_fit",
    engine: "reach",
    name: "Suppress the bad fit",
    logic: "Suppress lookalikes of one-and-done buyers",
    crossIndustry: "Every cycle",
    cycle_shape: ["replenishment", "recall", "expiry", "considered"],
    selector: {
      one_and_done: true,
      discount_affinity: ["discount_seeker"],
      consent_marketing: true,
    },
    guards: { min_audience: 50, cooldown_days: 30, max_discount_pct: 0 },
    offer: { type: "suppression_list" },
    copy_brief: { angle: "No copy — this is a suppression list", avoid: [] },
    priors: { response_rate: 1 },
    expected_order_value: 0,
  },
  {
    ...REACH_DEFAULTS,
    id: "recapture_unreachable",
    engine: "reach",
    name: "Reach the unreachable",
    logic: "Blocked LINE, withdrew consent, or too silent for a message to help",
    crossIndustry: "Where KEEP gives up and REACH takes over",
    cycle_shape: ["replenishment", "recall", "expiry", "considered"],
    selector: {
      reachable_by: ["paid_only"],
      monetary_percentile_min: 40,
      consent_marketing: true,
    },
    guards: { min_audience: 60, cooldown_days: 45, max_discount_pct: 0 },
    offer: { type: "paid_audience" },
    copy_brief: {
      angle: "They have not vanished — they moved somewhere only media reaches",
      avoid: [],
    },
    priors: { response_rate: 0.02 },
    expected_order_value: 2300,
  },
  {
    ...REACH_DEFAULTS,
    id: "retarget_lapsed_lead",
    engine: "reach",
    name: "Retarget stalled leads",
    logic: "Filled the form, no purchase inside the window",
    crossIndustry: "Every cycle",
    cycle_shape: ["considered", "recall"],
    selector: {
      lapsed_lead_days: [7, 60],
      no_purchase_ever: true,
      consent_marketing: true,
    },
    guards: { min_audience: 40, cooldown_days: 21, max_discount_pct: 0 },
    offer: { type: "paid_audience" },
    copy_brief: { angle: "Interested once, still undecided", avoid: [] },
    priors: { response_rate: 0.045 },
    expected_order_value: 1700,
  },
  {
    ...REACH_DEFAULTS,
    id: "expand_adjacent_category",
    engine: "reach",
    name: "Expand to adjacent categories",
    logic: "Seed from category A to open category B",
    crossIndustry: "Every cycle",
    cycle_shape: ["replenishment", "considered"],
    selector: {
      repeat_buyer: true,
      no_adjacent_category: true,
      consent_marketing: true,
    },
    guards: { min_audience: 80, cooldown_days: 45, max_discount_pct: 0 },
    offer: { type: "lookalike_seed" },
    copy_brief: { angle: "People who buy A are open to B", avoid: [] },
    priors: { response_rate: 0.025 },
    expected_order_value: 2000,
  },
];

export const ALL_PLAYS: Play[] = [...KEEP_PLAYS, ...REACH_PLAYS];

export function playById(id: string): Play | undefined {
  return ALL_PLAYS.find((p) => p.id === id);
}
